project:
  output-dir: CV

title: Hanne Oberman
toc: false
number-sections: false
# bibliography: references.bib  
  
format: 
  html: 
    page-layout: article
  # pdf:
  #   documentclass: report
  #   keep_tex: true
  #   include-in-header: 
  #   - text: \usepackage{fontawesome5}
  #   include-before-body: 
  #   - file: links.tex
theme: 
  - lux
  - lux.scss
css: styles.css
